-- Cấu trúc CSDL D1 cho app Phương Linh — SINH TỰ ĐỘNG từ worker/src/index.js (đừng sửa tay).
-- Không cần chạy file này bằng tay: trang migrate.html có nút "Kiểm tra & khởi tạo cấu trúc" gọi Worker tự tạo.
-- Chỉ để đọc tham khảo, hoặc dùng: npx wrangler d1 execute phuonglinh_erp --remote --file=schema.sql
CREATE TABLE IF NOT EXISTS "Config" ("Key" TEXT PRIMARY KEY, "Value" TEXT);
CREATE TABLE IF NOT EXISTS "NguoiDung" ("MaNV" TEXT PRIMARY KEY, "HoTen" TEXT, "TenDangNhap" TEXT, "MatKhauHash" TEXT, "VaiTro" TEXT, "TrangThai" TEXT, "NgayTao" TEXT, "SoLanSai" REAL, "KhoaDenLuc" TEXT);
CREATE TABLE IF NOT EXISTS "Phien" ("TokenHash" TEXT PRIMARY KEY, "MaNV" TEXT, "CreatedAt" TEXT);
CREATE TABLE IF NOT EXISTS "HangHoa" ("MaHH" TEXT PRIMARY KEY, "TenHH" TEXT, "Loai" TEXT, "DVT" TEXT, "GiaVonTB" REAL, "GiaBan" REAL, "TonKho" REAL, "TonKhoToiThieu" REAL, "GhiChu" TEXT, "NgayTao" TEXT, "DVTNhap" TEXT, "HeSoQuyDoi" REAL);
CREATE TABLE IF NOT EXISTS "NhaCungCap" ("MaNCC" TEXT PRIMARY KEY, "TenNCC" TEXT, "MST" TEXT, "DiaChi" TEXT, "SDT" TEXT, "Email" TEXT, "GhiChu" TEXT);
CREATE TABLE IF NOT EXISTS "KhachHang" ("MaKH" TEXT PRIMARY KEY, "TenKH" TEXT, "MST" TEXT, "DiaChi" TEXT, "SDT" TEXT, "Email" TEXT, "GhiChu" TEXT);
CREATE TABLE IF NOT EXISTS "NhapKho" ("IDPhieu" TEXT PRIMARY KEY, "Ngay" TEXT, "MaNCC" TEXT, "TenNCC" TEXT, "SoHDMuaVao" TEXT, "GhiChu" TEXT, "TongTienTruocThue" REAL, "TongTienThue" REAL, "TongTien" REAL, "DaTra" REAL, "NguoiTao" TEXT, "Timestamp" TEXT);
CREATE TABLE IF NOT EXISTS "NhapKhoCT" ("ID" INTEGER PRIMARY KEY, "IDPhieu" TEXT, "MaHH" TEXT, "TenHH" TEXT, "SoLuong" REAL, "DonGia" REAL, "ThanhTien" REAL, "ThueSuat" TEXT, "TienThue" REAL, "ThanhTienSauThue" REAL, "DVT" TEXT, "HeSoQuyDoi" REAL, "SoLuongQuyDoi" REAL);
CREATE TABLE IF NOT EXISTS "XuatBan" ("IDPhieu" TEXT PRIMARY KEY, "Ngay" TEXT, "MaKH" TEXT, "TenKH" TEXT, "MSTKhachHang" TEXT, "SoHDDT" TEXT, "KyHieuHD" TEXT, "GhiChu" TEXT, "TongTienTruocThue" REAL, "TongTienThue" REAL, "TongTien" REAL, "DaThu" REAL, "TrangThaiHD" TEXT, "NguoiTao" TEXT, "Timestamp" TEXT);
CREATE TABLE IF NOT EXISTS "XuatBanCT" ("ID" INTEGER PRIMARY KEY, "IDPhieu" TEXT, "MaHH" TEXT, "TenHH" TEXT, "SoLuong" REAL, "DonGia" REAL, "ThanhTien" REAL, "ThueSuat" TEXT, "TienThue" REAL, "ThanhTienSauThue" REAL, "DVT" TEXT, "HeSoQuyDoi" REAL, "SoLuongQuyDoi" REAL, "GiaVon" REAL);
CREATE TABLE IF NOT EXISTS "SuaChua" ("IDPhieu" TEXT PRIMARY KEY, "Ngay" TEXT, "MaKH" TEXT, "TenKH" TEXT, "SDT" TEXT, "ThietBi" TEXT, "TinhTrangTiepNhan" TEXT, "PhuKienKemTheo" TEXT, "NguoiPhuTrach" TEXT, "TrangThai" TEXT, "NgayHenTra" TEXT, "NgayHoanThanh" TEXT, "TienCong" REAL, "TienCongThueSuat" TEXT, "TienCongThue" REAL, "TongTienLinhKien" REAL, "TongTienLinhKienThue" REAL, "TongTienTruocThue" REAL, "TongTienThue" REAL, "TongTien" REAL, "DaThu" REAL, "SoHDDT" TEXT, "KyHieuHD" TEXT, "TrangThaiHD" TEXT, "BaoHanhNgay" REAL, "GhiChu" TEXT, "NguoiTao" TEXT, "Timestamp" TEXT);
CREATE TABLE IF NOT EXISTS "SuaChuaCT" ("ID" INTEGER PRIMARY KEY, "IDPhieu" TEXT, "MaHH" TEXT, "TenHH" TEXT, "SoLuong" REAL, "DonGia" REAL, "ThanhTien" REAL, "ThueSuat" TEXT, "TienThue" REAL, "ThanhTienSauThue" REAL, "DVT" TEXT, "HeSoQuyDoi" REAL, "SoLuongQuyDoi" REAL);
CREATE TABLE IF NOT EXISTS "GiaCong" ("IDPhieu" TEXT PRIMARY KEY, "Loai" TEXT, "Ngay" TEXT, "MaDoiTac" TEXT, "TenDoiTac" TEXT, "MoTaCongViec" TEXT, "SoLuongSanPham" REAL, "DonViTinh" TEXT, "ChiPhiGiaCongTruocThue" REAL, "ThueSuatGiaCong" TEXT, "TienThueGiaCong" REAL, "ChiPhiGiaCong" REAL, "TrangThai" TEXT, "NgayHenTra" TEXT, "NgayHoanThanh" TEXT, "DaThu" REAL, "DaTra" REAL, "SoHDDT" TEXT, "KyHieuHD" TEXT, "TrangThaiHD" TEXT, "GhiChu" TEXT, "NguoiTao" TEXT, "Timestamp" TEXT);
CREATE TABLE IF NOT EXISTS "GiaCongCT" ("ID" INTEGER PRIMARY KEY, "IDPhieu" TEXT, "MaHH" TEXT, "TenHH" TEXT, "SoLuong" REAL, "DonGia" REAL, "ThanhTien" REAL, "ThueSuat" TEXT, "TienThue" REAL, "ThanhTienSauThue" REAL, "DVT" TEXT, "HeSoQuyDoi" REAL, "SoLuongQuyDoi" REAL);
CREATE TABLE IF NOT EXISTS "SoQuy" ("IDPhieu" TEXT PRIMARY KEY, "Ngay" TEXT, "Loai" TEXT, "NhomMuc" TEXT, "SoTien" REAL, "PhuongThuc" TEXT, "NguonGoc" TEXT, "MoTa" TEXT, "NguoiTao" TEXT, "Timestamp" TEXT);
CREATE TABLE IF NOT EXISTS "NhatKyHoatDong" ("ID" INTEGER PRIMARY KEY, "Timestamp" TEXT, "NguoiDung" TEXT, "HanhDong" TEXT, "ChiTiet" TEXT);
CREATE TABLE IF NOT EXISTS "DieuChinhKho" ("ID" INTEGER PRIMARY KEY, "MaHH" TEXT, "Ngay" TEXT, "SoLuongQuyDoi" REAL, "DonGiaQuyDoi" REAL, "LyDo" TEXT, "NguoiTao" TEXT, "Timestamp" TEXT);
CREATE TABLE IF NOT EXISTS "SePayGiaoDich" ("MaGiaoDich" TEXT PRIMARY KEY, "ThoiGian" TEXT, "SoTien" REAL, "NoiDung" TEXT, "IDPhieu" TEXT, "KetQua" TEXT, "Timestamp" TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS "ix_nguoidung_tendangnhap" ON "NguoiDung" ("TenDangNhap");
CREATE INDEX IF NOT EXISTS "ix_phien_manv" ON "Phien" ("MaNV");
CREATE INDEX IF NOT EXISTS "ix_hanghoa_loai" ON "HangHoa" ("Loai");
CREATE INDEX IF NOT EXISTS "ix_ncc_mst" ON "NhaCungCap" ("MST");
CREATE INDEX IF NOT EXISTS "ix_kh_mst" ON "KhachHang" ("MST");
CREATE INDEX IF NOT EXISTS "ix_nhapkho_ngay" ON "NhapKho" ("Ngay");
CREATE INDEX IF NOT EXISTS "ix_nhapkho_ts" ON "NhapKho" ("Timestamp");
CREATE INDEX IF NOT EXISTS "ix_nhapkho_sohd" ON "NhapKho" ("SoHDMuaVao");
CREATE INDEX IF NOT EXISTS "ix_nhapkhoct_phieu" ON "NhapKhoCT" ("IDPhieu");
CREATE INDEX IF NOT EXISTS "ix_nhapkhoct_mahh" ON "NhapKhoCT" ("MaHH");
CREATE INDEX IF NOT EXISTS "ix_xuatban_ngay" ON "XuatBan" ("Ngay");
CREATE INDEX IF NOT EXISTS "ix_xuatban_ts" ON "XuatBan" ("Timestamp");
CREATE INDEX IF NOT EXISTS "ix_xuatban_sohd" ON "XuatBan" ("SoHDDT");
CREATE INDEX IF NOT EXISTS "ix_xuatbanct_phieu" ON "XuatBanCT" ("IDPhieu");
CREATE INDEX IF NOT EXISTS "ix_xuatbanct_mahh" ON "XuatBanCT" ("MaHH");
CREATE INDEX IF NOT EXISTS "ix_suachua_ngay" ON "SuaChua" ("Ngay");
CREATE INDEX IF NOT EXISTS "ix_suachua_ts" ON "SuaChua" ("Timestamp");
CREATE INDEX IF NOT EXISTS "ix_suachuact_phieu" ON "SuaChuaCT" ("IDPhieu");
CREATE INDEX IF NOT EXISTS "ix_suachuact_mahh" ON "SuaChuaCT" ("MaHH");
CREATE INDEX IF NOT EXISTS "ix_giacong_ngay" ON "GiaCong" ("Ngay");
CREATE INDEX IF NOT EXISTS "ix_giacong_ts" ON "GiaCong" ("Timestamp");
CREATE INDEX IF NOT EXISTS "ix_giacongct_phieu" ON "GiaCongCT" ("IDPhieu");
CREATE INDEX IF NOT EXISTS "ix_giacongct_mahh" ON "GiaCongCT" ("MaHH");
CREATE INDEX IF NOT EXISTS "ix_soquy_ngay" ON "SoQuy" ("Ngay");
CREATE INDEX IF NOT EXISTS "ix_soquy_nguongoc" ON "SoQuy" ("NguonGoc");
CREATE INDEX IF NOT EXISTS "ix_soquy_ts" ON "SoQuy" ("Timestamp");
CREATE INDEX IF NOT EXISTS "ix_nhatky_ts" ON "NhatKyHoatDong" ("Timestamp");
CREATE INDEX IF NOT EXISTS "ix_dieuchinh_mahh" ON "DieuChinhKho" ("MaHH");
